name: Trigger auto deployment for container-app-l55oh6u3ix52m

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-l55oh6u3ix52m-AutoDeployTrigger-9781ce18-54e5-44de-a39c-c1a24f41678f.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistryl55oh6u3ix52m.azurecr.io
          username: ${{ secrets.CONTAINERAPPL55OH6U3IX52M_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPL55OH6U3IX52M_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistryl55oh6u3ix52m.azurecr.io/container-app-l55oh6u3ix52m:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPL55OH6U3IX52M_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPL55OH6U3IX52M_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPL55OH6U3IX52M_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-l55oh6u3ix52m -g 20230330jobsdemob767 --server containerregistryl55oh6u3ix52m.azurecr.io --username  ${{ secrets.CONTAINERAPPL55OH6U3IX52M_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPL55OH6U3IX52M_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-l55oh6u3ix52m -g 20230330jobsdemob767 --image containerregistryl55oh6u3ix52m.azurecr.io/container-app-l55oh6u3ix52m:${{ github.sha }}
